name: Build Infinity APK

on:
  workflow_dispatch: {}         # para lanzarlo a mano
  push:
    branches: [ main ]          # opcional: al hacer push en main
  schedule:
    - cron: "0 6 * * *"         # opcional: diario 06:00 UTC

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # (Opcional) Mantener fork sincronizado con upstream
      - name: Sync with upstream
        run: |
          set -e
          git remote add upstream https://github.com/Docile-Alligator/Infinity-For-Reddit.git || true
          git fetch upstream
          git checkout main
          git merge --ff-only upstream/main || true
          git push origin main || true

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Android SDK
        run: |
          ANDROID_HOME="$HOME/android-sdk"
          mkdir -p "$ANDROID_HOME/cmdline-tools/latest"
          curl -sSL -o cmdtools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q cmdtools.zip -d "$ANDROID_HOME/cmdline-tools/latest"
          yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_HOME" \
            "platforms;android-30" "build-tools;30.0.3" "platform-tools"
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Inject API/UA/Redirect + Keystore
        env:
          REDDIT_API_TOKEN: ${{ secrets.REDDIT_API_TOKEN }}
          REDDIT_USERNAME:  ${{ secrets.REDDIT_USERNAME }}
          REDIRECT_URI:     ${{ secrets.REDIRECT_URI }}
          KEYSTORE_BASE64:  ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASS:    ${{ secrets.KEYSTORE_PASS }}
          KEY_ALIAS:        ${{ secrets.KEY_ALIAS }}
          KEY_PASS:         ${{ secrets.KEY_PASS }}
        run: |
          set -e
          API_FILE="app/src/main/java/ml/docilealligator/infinityforreddit/utils/APIUtils.java"

          # Sustituye token (client_id)
          sed -i "s/NOe2iKrPPzwscA/${REDDIT_API_TOKEN}/g" "$API_FILE"

          # Sustituye redirect
          sed -i "s#infinity://localhost#${REDIRECT_URI}#g" "$API_FILE"

          # USER_AGENT
          UA="android:personal-app:0.0.1 (by /u/${REDDIT_USERNAME})"
          sed -i 's/public static final String USER_AGENT = ".*";/public static final String USER_AGENT = "'"${UA//\//\\/}"'";/' "$API_FILE"

          # Keystore desde secret base64
          echo "$KEYSTORE_BASE64" | base64 -d > "$GITHUB_WORKSPACE/Infinity.jks"

          # Inserta signing config en app/build.gradle si no existe
          GRADLE_FILE="app/build.gradle"
          awk '
            BEGIN{ inserted=0 }
            /buildTypes[[:space:]]*\{/ && inserted==0 {
              print "    signingConfigs {"
              print "        release {"
              print "            storeFile file(\"" ENVIRON["GITHUB_WORKSPACE"] "/Infinity.jks\")"
              print "            storePassword \"" ENVIRON["KEYSTORE_PASS"] "\""
              print "            keyAlias \"" ENVIRON["KEY_ALIAS"] "\""
              print "            keyPassword \"" ENVIRON["KEY_PASS"] "\""
              print "        }"
              print "    }"
              print
              inserted=1
              next
            }
            { print }
          ' "$GRADLE_FILE" > tmp.gradle && mv tmp.gradle "$GRADLE_FILE"

          # Asegura referencia a signingConfig en release
          sed -i '0,/release[[:space:]]*{/{s/release[[:space:]]*{/release {\n            signingConfig signingConfigs.release/}' "$GRADLE_FILE"

          # (Opcional) baseline de Lint para evitar fallos por traducciones
          sed -i 's/disable '\''MissingTranslation'\''/disable '\''MissingTranslation'\''\n        baseline = file("lint-baseline.xml")/' "$GRADLE_FILE" || true

      - name: Build release
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon updateLintBaseline || true
          ./gradlew --no-daemon assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Infinity-Release-APK
          path: app/build/outputs/apk/release/*.apk
